---

- hosts: all
  become: true
  tasks:

    - name: update repo index 
      apt:
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: upgrade
      apt:
        upgrade: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: auto clean up
      apt:
        autoclean: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: auto remove
      apt:
        autoremove: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: update repo index 
      yum:
        update_cache: yes
      when: ansible_distribution == "CentOS" and ansible_distribution_version == "7.6"

    - name: upgrade
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == "CentOS" and ansible_distribution_version == "7.6"

    - name: auto remove
      yum:
        autoremove: yes
      when: ansible_distribution == "CentOS" and ansible_distribution_version == "7.6"

    - name: update repo index 
      yum:
        update_cache: yes
      when: ansible_distribution == "Rocky"

    - name: upgrade
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == "Rocky"

    - name: auto remove
      yum:
        autoremove: yes
      when: ansible_distribution == "Rocky"
