- name: install apache and php for Ubuntu servers
  tags: apache, apache2, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Pop!_OS"

- name: install apache and php for Rocky servers
  tags: apache, httpd, rocky
  dnf:
    name:
      - httpd
      - php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Rocky"

- name: install apache and php for CentOS servers
  tags: apache, httpd, centos
  yum:
    name:
      - httpd
      - php
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: start httpd (Rocky and CentOS)
  service: 
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution in ["Rocky", "CentOS"]

