- name: install mariadb package (Rocky)
  tags: db, mariadb, rocky
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Rocky"

- name: install mariadb package (CentOS)
  tags: db, mariadb, centos
  yum:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package (Pop!_OS)
  tags: db, mariadb, ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Pop!_OS"
